apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx
  namespace: homework
  labels:
    app: homework-app
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8000;
        root /homework;

        location / {
        autoindex on;
        }
        location /conf/file {
        alias /homework/conf/index.html;
        }
      }
    }